name: Get Latest Git Tag
description: Fetch the latest Git tag from the current GitHub repository
inputs: {}
outputs:
  latest_tag:
    description: "The latest Git tag"
    value: ${{ steps.get_tag.outputs.tag }}

runs:
  using: "composite"
  steps:
    - name: Get latest tag using GitHub API
      id: get_tag
      shell: bash
      run: |
        response=$(curl -s -H "Authorization: token $GITHUB_TOKEN" \
          https://api.github.com/repos/${{ github.repository }}/tags)
        latest_tag=$(echo "$response" | jq -r '.[0].name')
        echo "Latest tag: $latest_tag"
        echo "tag=$latest_tag" >> $GITHUB_OUTPUT
      env:
        GITHUB_TOKEN: ${{ github.token }}
